### PR TITLE
Improved gfycat support

### PR DESCRIPTION
**Pull request by JoshuaPotter**
Removed controls and added autoplay

### CODE REVIEW

**Comment by cosban** [comment]
I'll pull this if you make a setting that allows for auto-play. controllers should be enabled by default though.

**Comment by pbuzbee** [comment]
Strongly against autoplay by default. Many topics have a lot of webms, that's a lot of data to load and the conflicting noise is a nightmare.

Make it a setting, sure, but not by default.

**Comment by JoshuaPotter** [comment]
I thought the same initially, but the `<video>` tag loads the video on page load anyway, even if you don't click on the play button at all. All of the embeds are loading so they might as well be autoplayed so the user doesn't have to click play for every single one.

**Comment by JoshuaPotter** [comment]
[I could do something like this, though](http://stackoverflow.com/questions/14300141/how-to-prevent-html5-video-from-loading-before-playing)

**Comment by pbuzbee** [comment]
If you don't specify `autoplay` or `preload`, the browser decides what to do. [The recommendation is just to fetch the metadata](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload).

I'm fine with a setting for autoplay, but I don't think we should push it on everyone as the only option.

**Comment by JoshuaPotter** [comment]
All good ideas in here, I will get to work on this ASAP and update this pull request when I'm finished.

**Pull request closed without merging**
